name: classy
description: This is a package to simplify your dart code, specially classes and make your code more Classy and Cleaner without the normal boilerplate
version: 0.0.1-rc1
repository: https://github.com/Pedro-Ivo-Neves/Classy

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
